# Use Python 3.9 to avoid recent PyInstaller issue
# - https://stackoverflow.com/questions/68459087/pyinstaller-with-python-3-10-0b4-importerror-no-module-named-bootlocale
# - https://github.com/pyinstaller/pyinstaller/issues/5693
image: python:3.9.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pyinstaller
  - pip install -r requirements.txt

stages:
  - build

build windows:
  stage: build
  before_script:
    - choco install python --version=3.9.7 -y -f
    - refreshenv
    - "C:\\Python39\\python.exe -V"  # Print out python version for debugging
    - "C:\\Python39\\python.exe -m pip install pyinstaller"
    - "C:\\Python39\\python.exe -m pip install -r requirements.txt"
  script:
    - cd src/
    - "C:\\Python39\\Scripts\\pyinstaller.exe --onefile --windowed -n Pug main.py"
    - cd ../
  tags:
    - windows
  artifacts:
    paths:
      - src/dist/

build linux:
  stage: build
  script:
    - cd src/
    - pyinstaller --onefile --windowed -n Pug main.py
    - cd ../
  tags:
    - docker
  artifacts:
    paths:
      - src/dist/
